# Generated by Django 3.0.6 on 2020-07-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_idolranking_recommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
