# Generated by Django 3.0.6 on 2020-07-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_submissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissions',
            options={'verbose_name_plural': 'Submissions'},
        ),
    ]
