# Generated by Django 3.0.6 on 2020-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200707_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idolranking',
            name='rank_votes',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
